### PR TITLE
deps: upgrade redis-commands package

### PR DESCRIPTION
**Pull request by flintinatux**
This should open up access to Redis 5.0 streams as requested by #621, among others.

### CODE REVIEW

**Comment by luin** [comment]
🍻

**Comment by lakano** [comment]
Hello !
We need to use the Redis 5.0 streams commands. Currently on stable ioredis version 4.0.0, I can't uses the Redis 5.0 commands ( tested XADD in a redis.multi([ XADD ... ]).exec() )
Your commit sent one month ago seems to fix the problem, so I would like to known when a new version of ioredis will be submitted to permit us to uses it please?

**Comment by lakano** [comment]
Hello!
Thanks for the version 4.0.1 published 3 hours ago.
But, I don't understood, I can't uses « bzpopmin » command ( added in redis 5.0 ), and it's inside the package redis-commands 1.3.5 referenced in your package.json ( https://github.com/NodeRedis/redis-commands/blob/651d1592b7103cf045e0b0be0ca0532a19e6bfe9/commands.json ) 
Is it normal or do I need to report a bug on ioredis ( or may be in redis-commands ) ?
Thanks for your help!

**Comment by luin** [comment]
@lakano What the version of redis-commands installed in your project (you can see it via `npm ls | grep redis-commands`)?

**Comment by lakano** [comment]
The last one, 1.3.5, it's why it's really strange.. :-/

**Comment by lakano** [comment]
Nervermind, it's my Docker cache, sorry for the waste of time and thanks you for the upgrade! :)

**Comment by lakano** [comment]
Finally, I think there is a bug, I've recreated a simple example without Docker and from scratch, the bug is still present. Can you take a look on #716 please?

**Pull request merged**
