### PR TITLE
`_.extend` to `_.assign`

### PR DESCRIPTION
**Pull request by alsotang**
they are alias

### CODE REVIEW

**Comment by luin** [comment]
+1 for this, except `.DS_Store` should be ignored globally instead of being added to the project's .gitignore file since this kind of files are not ioredis specified.

**Comment by alsotang** [comment]
alright, if this pr seems ok, just ignore the .gitignore change

2015-09-06 18:13 GMT+08:00 Zihua Li <notifications@github.com>:

**Comment by luin** [comment]
You'd better amend this commit or just submit an other commit to revert the changes of .gitignore so that I can merge this pr directly. :rocket:

**Comment by alsotang** [comment]
I thought you would do this for me...

it's done

2015-09-06 19:45 GMT+08:00 Zihua Li <notifications@github.com>:

**Pull request merged**
