### PR TITLE
ISSUE-1024 keyPrefix option support Redis Cluster

### PR DESCRIPTION
**Pull request by cobolbaby**
https://github.com/luin/ioredis/issues/1024

### CODE REVIEW

**Comment by cobolbaby** [comment]
@luin Could the bugfix be merged into the trunk?

**Comment by eltonpao** [comment]
We're looking for this to be merged as well

**Comment by murbanowicz** [comment]
What about this bug? We hit this issue today

**Comment by luin** [comment]
Sorry for the late response. It was indeed an oversight but the fix is somehow a breaking change so I think we should ship this fix in the next major release. For now, we may add a usage notice to README.md to save people's time.

Thanks for the contribution @cobolbaby !

**Comment by murbanowicz** [comment]
To be honest I wouldn't consider it as breaking change but bugfix. 
At this moment ioredis basically does not respect keyPrefix provided in redisOptions which is expected way of doing that (reflected in typings) which is clearly a bug.

For this moment I had to add it to top-level options and it works with Cluster but this is hopefully not long term solution...

**Review by guruprasadgvmf — APPROVED** [review]
lookgs good

**Comment by guruprasadgvmf** [comment]
when is this shipping ?

**Comment by guruprasadgvmf** [comment]
why exactly is this a breaking change?

**Comment by lala7573** [comment]
This should be a bugfix.. or please update the documents :'( when is the next major release?

**Comment by luin** [comment]
Hey @cobolbaby 👋 
Sorry for the late response! Resolved this issue with #1522. Thanks for the contribution!

**Pull request closed without merging**
