### PR TITLE
Run prettier

### PR DESCRIPTION
**Pull request by imatlopez**

### CODE REVIEW

**Comment by imatlopez** [comment]
@luin using defaults to prettier, but I don't know if making line width 120 better, or using single quotes.

**Comment by imatlopez** [comment]
should src be added to the bundle in case people want to use the raw typings?

**Comment by luin** [comment]
> using defaults to prettier, but I don't know if making line width 120 better, or using single quotes.

I suggest sticking with the default settings of Prettier as close as possible since these settings are adopted by more people, making it easier for them to contribute to ioredis. (Although personally, I prefer to omit semicolons 🤣 .)

> should src be added to the bundle in case people want to use the raw typings?

Declarations will be included in the bundle if `declaration` is set to `true` in the tsconfig.json, so we don't need to bundle src into the package.

However, there is still something to do before bundling the declarations. The major one is Redis command methods are not declared, so TypeScript will complain about the usage like `redis.get(xxx).`. I'm already working on a solution for it, and after that, we can provide the official declarations.

**Comment by imatlopez** [comment]
@luin cool, in the meantime travis passed but seems the reporting hanged, and also I am attempting to use 4.11 on my end but there seems to be an issue with the asCallback in the `Redis.connect` function. :( good thing it is tagged as next for now

**Comment by luin** [comment]
> I am attempting to use 4.11 on my end but there seems to be an issue with the asCallback in the `Redis.connect` function.

What issue did you encountered?

**Comment by imatlopez** [comment]
Can't seem to connect, also I see some unhandled promise rejections now that we switched to promises

**Comment by imatlopez** [comment]
This is with v4.10.0
```bash
> ts-node ./source/integration-tests/createConnection

  ioredis:redis status[localhost:6379]: [empty] -> connecting +0ms
  ioredis:redis status[10.34.160.113:16430]: [empty] -> connecting +70ms
  ioredis:redis queue command[10.34.160.113:16430]: 0 -> sentinel([ 'get-master-addr-by-name', 'csc-redis-dev' ]) +1ms
  ioredis:redis status[10.34.160.113:16430]: connecting -> connect +14ms
  ioredis:redis status[10.34.160.113:16430]: connect -> ready +1ms
  ioredis:connection send 1 commands in offline queue +0ms
  ioredis:redis write command[10.34.160.113:16430]: 0 -> sentinel([ 'get-master-addr-by-name', 'csc-redis-dev' ]) +0ms
  ioredis:redis write command[10.34.160.113:16430]: 0 -> sentinel([ 'sentinels', 'csc-redis-dev' ]) +12ms
  ioredis:SentinelConnector adding sentinel 100.71.19.197:16430 +0ms
  ioredis:SentinelConnector Updated internal sentinels: {"sentinels":[{"host":"10.34.160.113","port":16430},{"host":"10.122.104.78","port":16430},{"host":"10.34.160.157","port":16430},{"host":"10.122.104.85","port":16430},{"host":"100.71.19.197","port":164 ... <REDACTED full-length="216"> +0ms
  ioredis:SentinelConnector resolved: 10.122.104.85:30241 +0ms
  ioredis:redis status[10.34.160.113:16430]: ready -> close +25ms
  ioredis:connection skip reconnecting since the connection is manually closed. +37ms
  ioredis:redis status[10.34.160.113:16430]: close -> end +0ms
  ioredis:redis status[10.122.104.85:30241]: connecting -> connect +1ms
  ioredis:redis write command[10.122.104.85:30241]: 0 -> info([]) +6ms
  ioredis:redis status[10.122.104.85:30241]: connect -> ready +12ms
  ioredis:redis write command[10.122.104.85:30241]: 0 -> set([ 'something', 'else' ]) +1ms
  ioredis:redis write command[10.122.104.85:30241]: 0 -> get([ 'something' ]) +12ms
  ioredis:redis status[localhost:6379]: [empty] -> connecting +12ms
  ioredis:redis status[10.122.104.85:30241]: ready -> close +15ms
  ioredis:connection skip reconnecting since the connection is manually closed. +59ms
  ioredis:redis status[10.122.104.85:30241]: close -> end +0ms
  ioredis:redis status[10.34.160.113:16430]: [empty] -> connecting +20ms
  ioredis:redis queue command[10.34.160.113:16430]: 0 -> sentinel([ 'get-master-addr-by-name', 'csc-redis-dev' ]) +0ms
  ioredis:redis status[10.34.160.113:16430]: connecting -> connect +13ms
  ioredis:redis status[10.34.160.113:16430]: connect -> ready +0ms
  ioredis:connection send 1 commands in offline queue +33ms
  ioredis:redis write command[10.34.160.113:16430]: 0 -> sentinel([ 'get-master-addr-by-name', 'csc-redis-dev' ]) +0ms
  ioredis:redis write command[10.34.160.113:16430]: 0 -> sentinel([ 'sentinels', 'csc-redis-dev' ]) +11ms
  ioredis:SentinelConnector adding sentinel 100.71.19.197:16430 +128ms
  ioredis:SentinelConnector Updated internal sentinels: {"sentinels":[{"host":"10.34.160.113","port":16430},{"host":"10.122.104.78","port":16430},{"host":"10.122.104.85","port":16430},{"host":"10.34.160.157","port":16430},{"host":"100.71.19.197","port":164 ... <REDACTED full-length="216"> +0ms
  ioredis:SentinelConnector resolved: 10.122.104.85:30241 +22ms
  ioredis:redis status[10.34.160.113:16430]: ready -> close +45ms
  ioredis:connection skip reconnecting since the connection is manually closed. +56ms
  ioredis:redis status[10.34.160.113:16430]: close -> end +0ms
  ioredis:redis status[10.122.104.85:30241]: connecting -> connect +1ms
  ioredis:redis write command[10.122.104.85:30241]: 0 -> info([]) +0ms
  ioredis:redis status[10.122.104.85:30241]: connect -> ready +12ms
  ioredis:redis write command[10.122.104.85:30241]: 0 -> set([ 'something', 'else' ]) +0ms
  ioredis:redis write command[10.122.104.85:30241]: 0 -> get([ 'something' ]) +11ms
..
OK
```

and this is with 4.11.0
``bash
ioredis:redis status[localhost:6379]: [empty] -> connecting +0ms
  ioredis:redis status[10.122.104.78:16430]: [empty] -> connecting +71ms
  ioredis:redis queue command[10.122.104.78:16430]: 0 -> sentinel([ 'get-master-addr-by-name', 'csc-redis-dev' ]) +1ms
  ioredis:redis status[10.122.104.78:16430]: connecting -> connect +16ms
  ioredis:redis status[10.122.104.78:16430]: connect -> ready +1ms
  ioredis:connection send 1 commands in offline queue +0ms
  ioredis:redis write command[10.122.104.78:16430]: 0 -> sentinel([ 'get-master-addr-by-name', 'csc-redis-dev' ]) +0ms
  ioredis:SentinelConnector resolved: 10.122.104.85:30241 +0ms
  ioredis:redis status[10.122.104.78:16430]: ready -> close +25ms
  ioredis:connection skip reconnecting since the connection is manually closed. +25ms
  ioredis:redis status[10.122.104.78:16430]: close -> end +1ms
  ioredis:redis status[10.122.104.85:30241]: connecting -> connect +0ms
  ioredis:redis write command[10.122.104.85:30241]: 0 -> info([]) +0ms
  ioredis:SentinelConnector role invalid, expected undefined, but got master +49ms
  ioredis:redis status[10.122.104.85:30241]: connect -> close +48ms
  ioredis:connection reconnect in 50ms +49ms
  ioredis:redis status[10.122.104.85:30241]: close -> reconnecting +0ms
  ioredis:redis status[10.122.104.85:30241]: reconnecting -> connecting +54ms
  ioredis:redis status[10.122.104.85:16430]: [empty] -> connecting +28ms
  ioredis:redis queue command[10.122.104.85:16430]: 0 -> sentinel([ 'get-master-addr-by-name', 'csc-redis-dev' ]) +0ms
  ioredis:redis status[10.122.104.85:16430]: connecting -> connect +11ms
  ioredis:redis status[10.122.104.85:16430]: connect -> ready +0ms
  ioredis:connection send 1 commands in offline queue +93ms
  ioredis:redis write command[10.122.104.85:16430]: 0 -> sentinel([ 'get-master-addr-by-name', 'csc-redis-dev' ]) +0ms
  ioredis:SentinelConnector resolved: 10.122.104.85:30241 +120ms
  ioredis:redis status[10.122.104.85:30241]: connecting -> connect +28ms
  ioredis:redis write command[10.122.104.85:30241]: 0 -> info([]) +0ms
  ioredis:redis status[10.122.104.85:16430]: ready -> close +1ms
  ioredis:connection skip reconnecting since the connection is manually closed. +29ms
  ioredis:redis status[10.122.104.85:16430]: close -> end +0ms
  ioredis:SentinelConnector role invalid, expected undefined, but got master +24ms
  ioredis:redis status[10.122.104.85:30241]: connect -> close +22ms
  ioredis:connection reconnect in 100ms +22ms
  ioredis:redis status[10.122.104.85:30241]: close -> reconnecting +0ms
  ioredis:redis status[10.122.104.85:30241]: reconnecting -> connecting +102ms
  ioredis:redis status[10.34.160.157:16430]: [empty] -> connecting +26ms
  ioredis:redis queue command[10.34.160.157:16430]: 0 -> sentinel([ 'get-master-addr-by-name', 'csc-redis-dev' ]) +0ms
  ioredis:redis status[10.34.160.157:16430]: connecting -> connect +11ms
  ioredis:redis status[10.34.160.157:16430]: connect -> ready +0ms
  ioredis:connection send 1 commands in offline queue +139ms
  ioredis:redis write command[10.34.160.157:16430]: 0 -> sentinel([ 'get-master-addr-by-name', 'csc-redis-dev' ]) +0ms
  ioredis:SentinelConnector resolved: 10.122.104.85:30241 +160ms
  ioredis:redis status[10.34.160.157:16430]: ready -> close +22ms
  ioredis:connection skip reconnecting since the connection is manually closed. +22ms
  ioredis:redis status[10.34.160.157:16430]: close -> end +7ms
  ioredis:redis status[10.122.104.85:30241]: connecting -> connect +0ms
  ioredis:redis write command[10.122.104.85:30241]: 0 -> info([]) +0ms
  ioredis:SentinelConnector role invalid, expected undefined, but got master +31ms

# forever
```

**Pull request merged**
