### PR TITLE
Use async/await

### PR DESCRIPTION
**Pull request by mjomble**
@luin I started working on the PR for #1314, but I'm finding the callback-based code a little difficult to work with.
I noticed that the async/await syntax is not used anywhere in this project.
Is there a reason for not using it? Or would you accept a PR that converts some of the code to this syntax?
I've included a small change in this draft PR, but I'll convert more if I get a green light 🙂

### CODE REVIEW

**Comment by luin** [comment]
hi @mjomble, thanks for the work!

ioredis still supports Node.js 6 (yeah I know it's pretty outdated...) so async function can't be used otherwise it will introduce a breaking change to codebases that uses v6.

We do have a plan for the next major version of ioredis with a batch of breaking changes, which will definitely include dropping the support of v6 (or maybe also v8...), so we should do the conversion at that point.

**Comment by mjomble** [comment]
With the current TypeScript configuration (target: es6) the async/await code gets transpiled into generator functions that are also supported in Node.js 6, so it should be fine.

To be sure, I ran the entire ioredis test suite on Node v6 and all tests passed (after I downgraded mocha to 6.2.3 since mocha 7 doesn't support Node 6 either).

**Comment by mjomble** [comment]
I pushed a few more commits. These also passed all tests on Node v6.

**Comment by luin** [comment]
Yeah that makes sense then. My only concern is whether the generated generators have any negative effects in terms of like performance or bundle size, especially given we're going to release a new major version soon so Node.js 6 won't be supported.


I'll take a look at this PR this week. Good catch for the mocha compatible issue btw!

**Comment by mjomble** [comment]
> My only concern is whether the generated generators have any negative effects in terms of like performance or bundle size

The transpiled SentinelConnector/index.js file did grow from 10205 to 10747 bytes in my local build. However, I assume this is a server-side library that doesn't normally get bundled into browser bundles.

As for performance, I'm not sure. But in any case, the current changes are limited to SentinelConnector. I imagine it could theoretically only cause performance problems if there were hundreds or thousands of disconnects and reconnects per second. Whereas sentinels typically wait several seconds before declaring a master unreachable.
A more realistic scenario with lots of rapid connector calls is automatic tests, which seemed to run equally fast with or without these changes.

**Comment by luin** [comment]
Fair enough. I just did a quick diff to the generated code and in general it lgtm. Will take a close look this week.

**Pull request merged**
