### PR TITLE
fix: srandmember with count argument should return array of strings or array of unknown

### LINKED ISSUE #1621: Type error, srandmember with count argument should return array of strings or array of unknown instead of string or array of unknowj
Hey,

In the current type implementation of `srandmember` with `count` argument the return type is `string | unknown[]` instead of `(string | unknown)[]` for returning multiple values

This is the entire type:
`srandmember(key: RedisKey, count: number | string, callback?: Callback<string | unknown[] | null>): Result<string | unknown[] | null, Context>;`

it should be:

`srandmember(key: RedisKey, count: number | string, callback?: Callback<(string | unknown)[] | null>): Result<(string | unknown)[] | null, Context>;`

Opening a PR for a fix

### PR DESCRIPTION
**Pull request by joni7777**
Closes #1621

### CODE REVIEW

**Comment by luin** [comment]
Hey @joni7777 👋 ,

Good catch! However, RedisCommander.ts is generated from bin/index.js so changes should be made on that file.

**Comment by joni7777** [comment]
@luin awesome, fixing

**Comment by joni7777** [comment]
@luin Fixed it, i think it supports now the two variants (with and without count)

**Comment by luin** [comment]
Made some changes. LMK if they make sense. @joni7777

**Comment by joni7777** [comment]
> Made some changes. LMK if they make sense. @joni7777 

Yea perfectly I think removing the unknown type is much better

**Pull request merged**
