### PR TITLE
add queue support for cluster failover & cluster down handling

### LINKED ISSUE #203: 100% CPU during cluster failover
Hi,

During a cluster failover, in the duration between the master died and the slave takes over (Basically redis `node-timeout` duration), the library seems to use 100% CPU.

I am obviously talking about loads of a few thousand requests per second.

### PR DESCRIPTION
**Pull request by shaharmor**
fixes #203

### CODE REVIEW

**Comment by shaharmor** [comment]
checks are failing in `master` branch too, so i don't think its related to this PR

**Comment by luin** [comment]
Thanks for the pull request! I'll take a look at it these days.

**Comment by shaharmor** [comment]
On my localhost redis cluster testing it seems so.

**Comment by luin** [comment]
Released in 1.12.1 :laughing:

**Pull request merged**
