### PR TITLE
Mention duplicate keys in scan stream example

### PR DESCRIPTION
**Pull request by philraj**
I've used a Set to handle the deduplication in the example, but I can switch it to a plain old object as I wrote in the comment if that feels less out of place.

### CODE REVIEW

**Comment by vweevers** [comment]
Using a Set to record visited keys is one solution, but having to keep all keys in memory can be a huge drawback. Another solution is to make your operations on the keys idempotent, so that it doesn't matter if you visit a key 1 time or 10 times.

What the best solution is depends on the use case, and I don't think ioredis docs should focus on that. Instead briefly explain the problem and leave it up to consumers to solve it.

**Comment by philraj** [comment]
@vweevers That's fair, but the original example was pushing them into an array, which would use even more memory (since duplicates are kept). I'm good with removing the storage of keys from the example entirely, simply logging from the `.on('data')` handler, and leaving the detail about duplicates as a simple comment.

**Comment by vweevers** [comment]
> I'm good with removing the storage of keys from the example entirely, simply logging from the .on('data') handler

Sounds good! That's also closer to the intention of streams

**Comment by luin** [comment]
Awesome! And thanks @vweevers for the advice!

**Pull request merged**
