### PR TITLE
fix: Fix autopipeline and downgrade p-map to support Node 6. [#1216]

### LINKED ISSUE #1216: The dependencie 'p-map' require node >= 10
I find that i can't run it in my project, my node is 6,  is it caused by this problem?

### PR DESCRIPTION
**Pull request by ShogunPanda**
## What's in there?

[x] Fixes a severe autopipeline bug that prevented correct routing.
[x] Fixes #1216 by downgrading `p-map` to `2.1.0`, which is the last one that supports Node 6.
[x] Changes the Travis matrix to run against all Node even version >= 6, plus the current unstable one.

## Note to reviewers

The autopipeline bug was not catch from the test suite since testing for cluster goes against a mock cluster.
Shall we change this to test against a real cluster?

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by AVVS** [comment]
Node 6 tests wont run due to dev deps requiring higher node version

As for using real cluster - its definitely an option

**Comment by ShogunPanda** [comment]
Ok, I'll remove it from the matrix then.
About the cluster, let me look at Travis documentation!

**Comment by ShogunPanda** [comment]
Node 6 removed.
I think this PR can land to fix the bugs.
I will take care of removing mock cluster in another PR.

**Comment by AVVS** [comment]
As soon as tests finish I'd be able to merge

**Pull request merged**
