### PR TITLE
truncate large/long debug output arguments

### PR DESCRIPTION
**Pull request by iamjochem**
wrap the debug node_module so that large/long debug output args are always truncated (avoids potentially MBs of data being outout to console).

this PR adds a module that offers a transparent wrap for the 3rd-party `debug` module, 
you just need to require `./utils/debug` in place of `debug` itself.

the idea for this PR was originally discussed here: https://github.com/luin/ioredis/issues/521

there are a couple of unit tests included.

### CODE REVIEW

**Comment by luin** [comment]
Nice patch! However, it seems that these changes may have a impact on the performance even when the debug mode is off (e.g. truncating strings).

I just found out that the debug module supports custom formatters. What about define a custom formatter for the arguments?

For example:

```
const createDebug = require('debug');
createDebug.formatters.a = (v) => {
  return genRedactedString(v, len);
};

module.exports = createDebug;

**Comment by iamjochem** [comment]
you are correct about the custom formatters - this is what I actually currently use to solve this issue in my own project. 

the reason I chose not to use custom formatters here is because they are applied "module" wide ... i.e. you may very well be overriding existing custom formatters or applying them (without asking) to all instances of "debug" used in a project's own code and all it's other dependencies (assuming they use the same version) ... I felt that this was something to be avoided (it is unfortunate that `debug` does not support custom formatters per 'instance')

the fix for the potential performance hit is easy enough - I pushed a commit that make the debug call a no-op (basically performing the same check as is done in the `debug` module itself) ... what do think?

**Comment by luin** [comment]
Awesome! Makes sense to me. I'll do some tests this weekend, and merge then.

**Comment by luin** [comment]
Released as v3.2.0. 🍺

**Comment by iamjochem** [comment]
@luin - thanks for merging, it's a goog feeling to start the week with a successful PR :-)

**Pull request merged**
