### PR TITLE
chore: get latest version from git tag

### PR DESCRIPTION
**Pull request by luin**

### CODE REVIEW

**Comment by luin** [comment]
The current NPM_TOKEN & GH_TOKEN are invalid, so we can test if the process works.

**Comment by AVVS** [comment]
checked the logs and travis does dynamic install based on platform (ci / install)
so maybe the following is fail proof:

install: `NPM_TOKEN="" GH_TOKEN="" /bin/sh -c 'npm ci || npm install'`

**Comment by luin** [comment]
According to the documentation of Travis CI, pull requests that sent from a forked repo won't have access to the encrypted env vars. I submitted a test pull request and the `NPM_TOKEN` & `GH_TOKEN` are not logged: https://travis-ci.org/luin/ioredis/jobs/442282959#L591.

**Comment by AVVS** [comment]
> According to the documentation of Travis CI, pull requests that sent from a forked repo won't have access to the encrypted env vars. I submitted a test pull request and the NPM_TOKEN & GH_TOKEN are not logged: https://travis-ci.org/luin/ioredis/jobs/442282959#L591.

Yeah, I was thinking more in the line of malicious dependencies. Such as with the eslint not so long ago. Where a build might be triggered from a "trusted" person

**Comment by luin** [comment]
That makes sense. We could just write the encrypted tokens as env vars to the `deploy` stage in .travis-ci.yml instead of configuring them in the dashboard of Travis CI that is visible by all the stages.

**Comment by AVVS** [comment]
> That makes sense. We could just write the encrypted tokens as env vars to the deploy stage in .travis-ci.yml instead of configuring them in the dashboard of Travis CI that is visible by all the stages.

agree, though I didn't find how to do that in travis

**Pull request merged**
