### PR TITLE
Add support for non-clustered replication without Sentinel

### PR DESCRIPTION
**Pull request by mvaker**
Hi!

I have made a few modifications to Cluster class to enable the support for replication cluster (which is intended to solve: https://github.com/luin/ioredis/issues/387).
I tried it in a project which I have a Redis cluster setup which doesn't use sharding but replication (master-slave full replicas) and it seems to work properly.

I would very much appreciate feedback about this feature and my resolution and I hope this branch gets merged some day so that we can all benefit from it and gets maintained.

### CODE REVIEW

**Comment by luin** [comment]
Thank you for the pull request! Could you give us more details of which problem this pr is intended to solve? I revisited #387 but read-write splitting is already supported in the Cluster mode.

**Comment by mvaker** [comment]
The problem is with read-write splitting in Cluster mode with replication (not with sharded clusters, nor sentinel). When in cluster mode, it always tries to search for a slot to which a command has to be sent, and if the cluster is a replication one (not sharding), it fails because all slots are in all nodes.

**Comment by AVVS** [comment]
> The problem is with read-write splitting in Cluster mode with replication (not with sharded clusters, nor sentinel). When in cluster mode, it always tries to search for a slot to which a command has to be sent, and if the cluster is a replication one (not sharding), it fails because all slots are in all nodes.

Its not a cluster - its a replicated single machine setup. Master - Slave, which should use sentinel for monitoring and automatic failover. It seems there is confusion over a cluster and sentinel.

@mvaker what you are referring to is a sentinel based setup (should be)

**Comment by mvaker** [comment]
Hello! Thanks for your early comments.
It is not a Sentinel based setup, we are using this setup (cluster mode dissbled): 
http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/Replication.Redis-RedisCluster.html

http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/AutoFailover.html

It does pretty much the same as sentinel but amazon provides it all itself (failover, monitor, etc). So it's a redis cluster without sharding (or with all shards in the same node), but since it's elasticache it's not sentinel based.
I have not tried the sentinel client here, but I understand it won't work either because no sentinel commands are available.
I think that the best approach is to use the cluster mode to keep track of existing nodes and connection pool, while sending reads to random reader (slave) instances.
Thank you!

**Comment by mvaker** [comment]
BTW my resolution in this PR is a little bit "dirty" and I know this can probably be done better (maybe a separate class or client..). It was just a quick approach to see if it worked and hear what are your thoughts about it.

**Comment by mvaker** [comment]
Hi, any thoughts on this? Have you checked my last comments? I would appreciate very much any comments. Thank you.

**Comment by christoph-puppe** [comment]
Would love to see that. Don't need sentinel and no cluster. Just read-only slaves for 90% of the load but need to get the 10% writes to the master @luin 

My usecase: frontend nodes are too far away for cluster, so latency is high. Solution: have a slave per frontend-instance and speed up the whole thing for reads.

**Comment by fenichelar** [comment]
This is a much needed feature! The AWS non-clustered approach is much better for write heavy workflows than clustering because AWS only supports on-the-fly resizing for non-clustered Redis.

**Comment by fenichelar** [comment]
@mvaker You should probably rename this PR to "Add AWS non-clustered replication support" for clarity. This is not clustering.

**Comment by mvaker** [comment]
hi @luin, I would like to discuss again this PR, so clearly this is a missing feature in this library and other people have proved it being useful for them. Thanks a lot!

**Comment by luin** [comment]
Sorry for the late response. I've been thinking about whether this feature should be in a separate module since ioredis is focused on the official Redis features instead of the platform-specified ones.

**Comment by fenichelar** [comment]
@luin The problem is the assumption that either Sentinel or Cluster mode are used if replication is used. Redis supports replication without Sentinel or Cluster mode but `ioredis` does not and therefore does not support read/write splitting for the following 3 use cases:
- Vanilla Redis without Sentinel but with master/slave replication (which is perfectly valid for read heavy workloads)
- Redis Enterprise
- AWS ElastiCache in non-cluster mode
While I haven't looked into the contents of the PR, I think the feature is well within the scope of scenarios `ioredis` should support natively.

**Comment by STRML** [comment]
This is particularly useful if you just have heavy read or pub/sub flow on a local machine and need more cores to process the subscriptions.

**Comment by fenichelar** [comment]
@mvaker I said you should probably rename this PR to "Add AWS non-clustered replication support" but I think that is misleading, my fault. Instead, "Add support for non-clustered replication without Sentinel" is probably more accurate. While AWS is a use case, there are other use cases where this PR is quite useful. @STRML just brought up yet another use case.

@luin I use Redis Enterprise and `ioredis` (hosted on AWS lol). At some point, I am going to have more read traffic on a single key than a single shard in Redis Enterprise can handle. So adding another shard to the Redis Enterprise cluster will not help. I will have to create a read replica of the cluster so the same key is stored on different shards. The replication is managed by Redis Enterprise, not Sentinel. Having `ioredis` support this natively would be very nice :)

**Comment by caffeineshock** [comment]
Hey @luin, what's your current feeling about this pull request? Do you think it will get merged into the source eventually or are you rather inclined towards the separate modules solution?

We are currently stuck with a cluster that is not managed by sentinel and need to use read/write splitting quite soon. If this pull request might get merged soon, we would like to use the introduced feature. Otherwise we will have to split reading and writing manually by using different clients.

**Comment by christoph-puppe** [comment]
Any news?

**Comment by STRML** [comment]
FWIW, we worked on a fork of this PR for a while, and abandoned it in favor of just putting HAProxy in front of a bunch of read slaves, opening port 6378, and having all the pub/sub clients connect to that. That way, the adapter doesn't have to know anything (this logic is brittle, particularly in regards to reconnects).

**Comment by azman0101** [comment]
Is there any chance that these use-case described in this issue will be one day supported ?

This redis chart https://github.com/helm/charts/tree/master/stable/redis also support replication cluster.

https://redis.io/topics/replication

**Pull request closed without merging**
