### PR TITLE
Do not modify input parameters

### PR DESCRIPTION
**Pull request by ccs018**
This should resolve issue #503.  The test app from #503 works.

### CODE REVIEW

**Comment by AVVS** [comment]
Change as it is will work, but, at the same time, there will be a performance penalty associated with this, as we'd have to create shallow copies of args for each command

@luin what do you think?

**Comment by ccs018** [comment]
It appears that this PR isn't needed.  There is another commit on (June 8th) for #480 which also appears to resolve the issue and would probably explain why @luin wasn't able to reproduce it:  I'm using the released 3.1.1 and @luin was likely running off of the latest code.  3.1.1 does not include the commit for #480.

If that's the case, then this PR can be rejected.

3.1.1 code:
```
Pipeline.prototype.addBatch = function (commands) {
  for (var i = 0; i < commands.length; ++i) {
    var command = commands[i];
    var commandName = command.shift();
    this[commandName].apply(this, command);
  }

  return this;
};
```

Latest version:
```
Pipeline.prototype.addBatch = function (commands) {
  var command, commandName, args;
  for (var i = 0; i < commands.length; ++i) {
    command = commands[i];
    commandName = command[0];
    args = command.slice(1);
    this[commandName].apply(this, args);
  }

  return this;
};
```

**Comment by luin** [comment]
@ccs018 Thank you for pointing this out! Just released v3.1.2. Sorry for not released this version when the fixed had been ma

**Comment by ccs018** [comment]
Thanks for the updated release!

**Pull request closed without merging**
